### ISSUE TITLE
Use Semantic Versioning

### ISSUE THREAD

**Issue by tomaszkane** [thunderer/Platenum#2]
Hi,
it would be great to use https://semver.org/.
So if package is stable, release 1.0.0, what do you think?

BTW, good presentation on Warsaw PHPers#19.

**Comment by thunderer** [comment]
@tomaszkane Thanks, it's certainly a good idea. The **library is stable**, I just wanted to wait a few days for the first issues or suggestions. I will tag `v1.0.0` shortly.

Did you or do you plan to use Platenum in your projects?

**Comment by tomaszkane** [comment]
Good.

@thunderer I already use it, and have first tiny suggestion... ?
Code autocomplete with 'self' in PhpDoc (suggested in readme) fail:

```php
<?php

namespace common\enums;

use Thunder\Platenum\Enum\ConstantsEnumTrait;

/**
 * @method static UserRewardStatus NEW()
 * @method static self PROCESSING()
 */
final class UserRewardStatus
{
    private const NEW = 1;
    private const PROCESSING = 2;

    use ConstantsEnumTrait;

    private function fooBar()
    {
        $foo = UserRewardStatus::NEW()->getValue();
        $boo = UserRewardStatus::PROCESSING()->getValue();
    }
}
```

For `$boo`, PhpSorm 2019.2 says: _Method 'getValue()' not found in self_.
It's not a big deal, but... you know.

**Comment by thunderer** [comment]
@tomaszkane that's interesting - I modified and expanded your example a bit (the code below), and all variants of `self` are autocompleted (ie. `Enum::MEMBER()` suggestions) but the result is not recognized as instance of that class. Turns out that if you swap `self` for `static` it works correctly, so please use `@method static static MEMBER()`. I didn't find any PHPStorm bugs related to this behavior, but for me it looks like one. I will update README and generator to reflect this change. Thanks for pointing it out!

By the way, is there any reason why you create the enum member instances inside the enumeration class? Or is that only for demonstration purposes?

```php
/**
 * @method static InternalUsage XCLASS()
 * @method static self XSELF()
 * @method static static XSTATIC()
 */
final class InternalUsage
{
    private const XCLASS = 1;
    private const XSELF = 2;
    private const XSTATIC = 3;

    use ConstantsEnumTrait;

    private function yeah(): void
    {
        $foo = InternalUsage::XCLASS()->getValue();
        $bar = InternalUsage::XSELF()->getValue();
        $baz = InternalUsage::XSTATIC()->getValue();

        $foo = self::XCLASS()->getValue();
        $bar = self::XSELF()->getValue();
        $baz = self::XSTATIC()->getValue();

        $foo = static::XCLASS()->getValue();
        $bar = static::XSELF()->getValue();
        $baz = static::XSTATIC()->getValue();
    }
}

final class ExternalUsage
{
    public function yeah(): void
    {
        $foo = InternalUsage::XCLASS()->getValue();
        $bar = InternalUsage::XSELF()->getValue();
        $baz = InternalUsage::XSTATIC()->getValue();
    }
}
```

**Comment by thunderer** [comment]
@tomaszkane could you please take a look at my comment above and changes in #3? Let me know if this resolves your issue.

**Comment by tomaszkane** [comment]
@thunderer my code is only demonstration :-)
I run you code in my IDE and yes, "self" fail, "static" and "ClassName" works. Thanks.

**Comment by tomaszkane** [comment]
Hm, live usage:

```php
<?php

namespace common\enums;

use Thunder\Platenum\Enum\ConstantsEnumTrait;

/**
 * @method static self NEW()
 * @method static static PROCESSING()
 * @method static UserRewardStatus SHIPPED()
 */
final class UserRewardStatus
{
    private const NEW = 1;
    private const PROCESSING = 2;
    private const SHIPPED = 3;

    use ConstantsEnumTrait;
}

```

```php
<?php

namespace api\actions;

use common\enums\UserRewardStatus;
use common\models\UserToReward;


class RewardsOrderAction extends \yii\rest\CreateAction
{

    public function run()
    {
        $userReward = new UserToReward();
        $userReward->status = UserRewardStatus::NEW()->getValue();
        $userReward->status = UserRewardStatus::PROCESSING()->getValue();
        $userReward->status = UserRewardStatus::SHIPPED()->getValue();
    }

}

```

In `RewardsOrderAction` PhpStorm autocomplete is freak...
for NEW - no completion, "getValue() not found"
for PROCESSIG - has completion, but "getValue() not found" ?!
for SHIPPED - has completion and found "getValue()"

I think it's IDE problem, not Platenum.

**Comment by thunderer** [comment]
@tomaszkane Have you tried clearing IDE cache (`File > Invalidate Caches / Restart`)? PHPStorm acts weirdly from time to time and this usually fixes the problem.

By the way, since the original issue seems to be resolved, can we close this issue? I plan to publicly announce Platenum in other places and gather more information about its usage - the `v1.0` release will follow shortly after, possibly in the next few weeks.

**Comment by tomaszkane** [comment]
When PHPStorm stoped autocomplte me everything (a few time in past) invalidate cache done good work, bu not in this case. Anyway let's close this issue.
